trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'gabrielfranh/testapi'  # Nome do repositório Docker Hub
  IMAGE_TAG: '$(Build.BuildId)'       # Tag da imagem Docker

steps:
# Build and Push Docker Image
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'  # Nome da conexão Docker Hub
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'                # Caminho para seu Dockerfile
    tags: '$(IMAGE_TAG)'

# Configure AWS CLI
- script: |
    aws configure set aws_access_key_id $(awsAccessKeyId)
    aws configure set aws_secret_access_key $(awsSecretAccessKey)
    aws configure set region us-east-1
  displayName: 'Configure AWS CLI'
  env:
    AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
    AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)

# Download the Kubeconfig
- task: DownloadSecureFile@1
  name: downloadKubeConfig
  inputs:
    secureFile: 'kubeconfig-eks'

# Apply or Update Kubernetes Deployment
- script: |
    export AWS_ACCESS_KEY_ID=$(awsAccessKeyId)
    export AWS_SECRET_ACCESS_KEY=$(awsSecretAccessKey)
    export AWS_DEFAULT_REGION=us-east-1
    export KUBECONFIG=$(downloadKubeConfig.secureFilePath)

    # Check if the deployment exists
    if kubectl get deployment/testapi-dp > /dev/null 2>&1; then
        # Update the existing deployment with the new image
        kubectl set image deployment/testapi-dp testapi=$(IMAGE_NAME):$(IMAGE_TAG)
    else
        # Apply the deployment and service manifests if they don't exist
        kubectl apply -f $(System.DefaultWorkingDirectory)/deployment.yaml
        kubectl apply -f $(System.DefaultWorkingDirectory)/service.yaml
    fi
  displayName: 'Create or Update Kubernetes Deployment'
