trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'gabrielfranh/testapi'
  IMAGE_TAG: '$(Build.BuildId)'

steps:
# Build and Push Docker Image
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(IMAGE_TAG)'

# Configure AWS CLI
- script: |
    aws configure set aws_access_key_id $(awsAccessKeyId)
    aws configure set aws_secret_access_key $(awsSecretAccessKey)
    aws configure set region us-east-1
  displayName: 'Configure AWS CLI'
  env:
    AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
    AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)

# Download the Kubeconfig
- task: DownloadSecureFile@1
  name: downloadKubeConfig
  inputs:
    secureFile: 'kubeconfig-eks'

# Apply the Kubernetes Deployment
- script: |
    export KUBECONFIG=$(downloadKubeConfig.secureFilePath)
    minha-api=$(IMAGE_NAME):$(IMAGE_TAG)
    kubectl set image deployment/testapi-dp testapi=$(IMAGE_NAME):$(IMAGE_TAG)
  displayName: 'Update deployment to new image'
