apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-dp
  labels:
    app: testapi-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi-dp
  template:
    metadata:
      name: testapi-dp
      labels:
        app: testapi-dp
    spec:
      containers:
        - name: testapi-container
          image: gabrielfranh/testapi:dev
          imagePullPolicy: Always
          ports:
          - containerPort: 5299
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://*:5299"