apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapi-dp
  labels:
    app: testapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapi
  template:
    metadata:
      name: testapi-pod
      labels:
        app: testapi
    spec:
      containers:
        - name: testapi-container
          image: gabrielfranh/testapi:$(IMAGE_TAG)
          imagePullPolicy: Always
          ports:
          - containerPort: 5299
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://*:5299"